### ISSUE TITLE
AND/OR filtering

### ISSUE THREAD

**Issue by jotto** [Fosome/garb#22]
I see the README says that documentation for AND/OR is on the TODO, but I think that the DSL might not be currently capable of properly OR filtering.

The following works.... but how do you generate it programmatically? I can't build a Ruby Hash of duplicate keys.

```
report.filters({:page_path.eql => 'index', :page_path.eql => 'home'})
```

So I try the block method

```
report.filters do
    ['index', 'home'].each do |path|
        eql(:page_path, path)
    end
end
```

But that ends up using the AND operator: `filters=ga:pagePath%3D%3Dindex;ga:pagePath%3D%3Dhome`

So I try the next obvious thing:

```
report.filters do
    eql(:page_path, ['index', 'home'])
end
```

But that just results in `filters=ga:pagePath%3D%3Dindexhome` when it should be `filters=ga:pagePath%3D%3Dindex,ga:pagePath%3D%3Dhome`

Anyone get this working or should we rework this part of the DSL?

**Comment by tpitale** [comment]
Okay, so, looking at old versions of the Data Export API, before they supported OR operators, what was the AND operator is now the OR operator. Great! I must have missed this.

Because what you say is true (hash keys are unique) and only OR's may have the same key I will make the following DSL work:

<pre><code># Two hashes are OR'd together, key/values in a hash are AND'd together
report.filters {:page_path => 'index'}, {:page_path => 'home'}
</code></pre>

**Comment by tpitale** [comment]
Garb version 0.7.2 is out with this API solidified.

Here's the documentation for using AND/OR in filtering: http://wiki.github.com/vigetlabs/garb/filtering-with-andor

Let me know if more needs to be done.
