### ISSUE TITLE
can't create multiple filters against the same target with the same method

### ISSUE THREAD

**Issue by aconbere** [Fosome/garb#24]
Because the < and > operators don't work against dimensions, in order to build ranges targeting dimensions such as daysSinceLastVisit, one would like to do something akin to

<pre><code>
filters do
  [1..7].each {|i| eql(:days_since_last_visit, i) }
end
</code></pre>

Because Garb uses a hash to store the filters, and keys that hash on the (target, operator) pair, doing this appears to be impossible.

Thoughts?

**Comment by aconbere** [comment]
maybe my first tests were wrong, I've emulated this behavior this way

<pre><code>
  filters :days_since_last_visit.eql => 7
  filters :days_since_last_visit.eql => 6
  filters :days_since_last_visit.eql => 5
  filters :days_since_last_visit.eql => 4
  filters :days_since_last_visit.eql => 3
  filters :days_since_last_visit.eql => 2
  filters :days_since_last_visit.eql => 1
  filters :days_since_last_visit.eql => 0
</code></pre>

**Comment by tpitale** [comment]
I'm not certain what they net effect of all this is. Either way, your comment is correct. You can re-use the filters method and it will OR them together (because you can't have something that is both 5 AND 6 days since last visit).

A shorthand for this my be:

<pre><code>filters *([1..7].map { |i| {:days_since_last_visit.eql => i} })</code></pre>

**Comment by tpitale** [comment]
Just to clarify, that code creates an array of hashes containing the filter on days_since_last_visit equal to each day, and then unpacks it for passage to filters.

**Comment by tpitale** [comment]
The reason the first example did not work was because filters within one block will be AND'd together, and you can't have a metric/dimension as a filter that is two things at once.

This also occurs practically from the use of hashes. You can use the same metric with two distinct symbol operators (>= and <= on the same metric).

**Comment by aconbere** [comment]
the shorthand in your first comment is absolutely what I was going for. Digging into the garb code I recognized quickly that you were storing a list of hashes (not just a hash), but the methods of manipulating that were rather opaque.

At first I thought that the choice of a hash as the containing data structure was just flawed, and that it would be better implemented as a list where insertion offered an api to limit duplicates. But I think that the list of hashes is actually pretty solid, but that the current api makes it... unclear which of the two effects you're creating are. Are you adding the hash to a list... or are you adding an element to the hash...

Anyway... thanks for the prompt response, I'd call this closed :)

**Comment by tpitale** [comment]
You're welcome.

I've only just recently clarified the AND/OR behavior and reconciled with the GA api docs. This is still a work-in-progress.
