### ISSUE TITLE
Broken after gem update

### ISSUE THREAD

**Issue by HuckyDucky** [Fosome/garb#77]
I updated the gems in my Rails 3 application, and now I'm left with:

undefined method `eql' for :hostname:Symbol

on this call:

```
for visit in Visits.results(profile, :start_date => (Date.today-numdays), :filters => { :hostname.eql => "#{@brand.subdomain}.mysite.net" })
```

What is it that Garb depends on that breaks this?

**Comment by tpitale** [comment]
Symbol operators are tricky little bastards. I'd like to remove them entirely since they conflict with the symbol operators from DataMapper, and a few other ORM querying interfaces. MongoMapper is the only one that works currently.

I'll have to try Garb out in Rails 3 again, but please let me know if you are using any of these libraries.

Thanks!
